main: mainArray.c mainArrayVBO.c mainTriangles.c
	gcc -o mainArray.o mainArray.c -lGL -lGLU -lglut -lGLEW -lSOIL -lm
	gcc -o mainArrayVBO.o mainArrayVBO.c -lGL -lGLU -lglut -lGLEW -lSOIL -lm
	gcc -o mainTriangles.o mainTriangles.c -lGL -lGLU -lglut -lGLEW -lSOIL -lm